local hop = require("hop")
local hint = require("hop.hint")

require("hop").setup({})

vim.keymap.set("", "<left>", function()
	hop.hint_char1({ direction = hint.HintDirection.BEFORE_CURSOR })
end)
vim.keymap.set("", "<right>", function()
	hop.hint_char1({ direction = hint.HintDirection.AFTER_CURSOR })
end)
vim.keymap.set("", "<up>", function()
	hop.hint_vertical({ direction = hint.HintDirection.BEFORE_CURSOR })
end)
vim.keymap.set("", "<down>", function()
	hop.hint_vertical({ direction = hint.HintDirection.AFTER_CURSOR })
end)
vim.keymap.set("", "<M-f>", hop.hint_patterns)
