-- TODO: sort
require('config.colorscheme')
require('config.ultisnips')
-- require('config.osc52')
require('config.smartyank')
require('config.noice')
-- require('config.null')
require('config.vmath')
require('config.comment')
require('config.illuminate')
require('config.formatting')
require('config.hop')
require('config.lines')
require('config.delback')
require('config.indentblankline')
require('config.refactoring')
require('config.neogen')
-- require('config.dressing')
require('config.gps')
require('config.gitsigns')
require('config.easyalign')
require('config.commentframe')
require('config.treesitter')
-- require('config.lspsignature')
-- require('config.notify')
require('config.telescope')
require('config.cheat')
require('config.autopairs')
require('config.repmotion')
-- require('config.marks')
