vim.keymap.set('n', '<localLeader>f', '<cmd>Telescope git_files theme=dropdown<cr>')
vim.keymap.set('n', '<localLeader>g', '<cmd>Telescope grep_string theme=dropdown<cr>')
vim.keymap.set('n', '<localLeader>b', '<cmd>Telescope buffers theme=dropdown<cr>')
vim.keymap.set('n', '<localLeader>s', '<cmd>Telescope treesitter theme=dropdown<CR>')
vim.keymap.set('n', '<localleader>l', function() vim.cmd("Telescope lsp_workspace_symbols theme=dropdown query=" .. vim.fn.expand("<cword>")) end)
