# ~/.config/starship/starship.toml

# $username\
# $hostname\
# $shell\

format = """
$shlvl\
$singularity\
$kubernetes\
$sudo\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$cobol\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$env_var\
$crystal\
$custom\
$time\
$cmd_duration\
$line_break\
$jobs\
$battery\
$status\
$character"""

[sudo]
format = "[$symbol]($style)"
disabled = false

[aws]
symbol = "  "

[conda]
symbol = " "
format = "[$symbol$environment]($style) "

[dart]
symbol = " "

[directory]
read_only = " "
format = "[ $path]($style)[$read_only]($read_only_style) "
home_symbol = " ~"

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "
format = "[$symbol$branch ]($style)"

[git_commit]
format = "[\\($tag\\) ]($style)"

[git_status]
format = '([\[$all_status$ahead_behind\] ]($style))'

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[package]
symbol = " "
format = "[$symbol$version ]($style)"

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "
format = '[${symbol}${pyenv_prefix}(${version})( \($virtualenv\)) ]($style)'

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[swift]
symbol = "ﯣ "

[character]
success_symbol = "[  ](bright-black)"
error_symbol = "[ ](bright-black)"

[line_break]
# disabled = true
disabled = false

[username]
format = "[$user ]($style)"

[hostname]
format = "[$hostname ]($style)"

[status]
disabled = false
format = "[$status ]($style)"

[shell]
disabled = false
format = "[$indicator ](bold blue)"

[time]
disabled = false
format = "[$time ](bold)"

[cmd_duration]
format = "\\([$duration](white)\\)"

# GIT STATUS
# conflicted "=" 
# ahead 	 "⇡" 	
# behind 	 "⇣" 	
# diverged 	 "⇕" 	
# up_to_date "" 	
# untracked  "?" 
# stashed 	 "$" 	
# modified 	 "!" 	
# staged 	 "+" 	
# renamed 	 "»" 	
# deleted 	 "✘"
