theme = "default"

[editor]
mouse = false
cursorline = true
scrolloff = 0
gutters = [
    "diff",
    "diagnostics",
    "line-numbers",
    "spacer",
]
preview-completion-insert = false
auto-info = true
bufferline = "multiple"

[editor.statusline]
left = [
    "file-name",
    "version-control",
    "diagnostics",
    "read-only-indicator",
    "file-modification-indicator",
]
center = []
right = [
    "spinner",
    "selections",
    "register",
    "position",
]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.search]
wrap-around = false

[editor.indent-guides]
render = false
skip-levels = 1

[editor.soft-wrap]
enable = true
max-wrap = 0
max-indent-retain = 0

[editor.smart-tab]
enable = false

[editor.inline-diagnostics]
cursor-line = "hint"

[keys.normal]
0 = "extend_line"
- = "goto_line"
Z = ":write"
esc = [
    "collapse_selection",
    "keep_primary_selection",
]
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
q = "move_next_sub_word_end"
Q = "move_prev_sub_word_end"
h = "goto_first_nonwhitespace"
j = "@12zk"
k = "@12zj"
l = "goto_line_end"
A-h = "move_char_left"
A-j = "move_visual_line_down"
A-k = "move_visual_line_up"
A-l = "move_char_right"
"A-]" = [
    "extend_to_line_bounds",
    "delete_selection",
    "paste_after",
]
"A-[" = [
    "extend_to_line_bounds",
    "delete_selection",
    "move_line_up",
    "paste_before",
]
C-g = ''':echo "%{cursor_line}:%{cursor_column}; %sh{cat %{buffer_name} | wc -l | tr -d ' '} lines --%sh{python -c ""print(round(%{cursor_line} / $(cat %{buffer_name} | wc -l | tr -d ' ') * 100))""}%%--"'''

[keys.normal.g]
q = ":quit!"
