[[language]]
name = "python"
auto-format = true
language-servers = ["pyright", "jedi"]
formatter = { command = "black", args = ["--quiet", "-"] }

[[language]]
name = "markdown"
comment-tokens = ["-", "+", "*", "- [ ]", ">"]
