[colors]
ansi = [
  '#24292e',
  '#d73a49',
  '#28a745',
  '#dbab09',
  '#0366d6',
  '#5a32a3',
  '#0598bc',
  '#6a737d',
]
background = '#f4f4f4'
brights = [
  '#959da5',
  '#cb2431',
  '#22863a',
  '#dbab09',
  '#005cc5',
  '#5a32a3',
  '#3192aa',
  '#d1d5da',
]
cursor_bg = '#044289'
cursor_border = '#044289'
cursor_fg = '#f4f4f4'
foreground = '#282828'
selection_bg = '#dbe9f9'
selection_fg = '#24292f'

[colors.indexed]

[metadata]
name = 'github-light'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
