[colors]
ansi = [
  '#0F1419',
  '#F07178',
  '#B8CC52',
  '#F29718',
  '#36A3D9',
  '#FFEE99',
  '#B8CC52',
  '#FFFFFF',
]

background = '#0F1419'
brights = [
  '#3E4B59',
  '#F62217',
  '#B8CC52',
  '#F29718',
  '#36A3D9',
  '#FFB454',
  '#B8CC52',
  '#5C6773',
]
cursor_bg = '#F29718'
cursor_border = '#F29718'
cursor_fg = '#0F1419'
foreground = '#FFEE99'
selection_bg = '#253340'
selection_fg = '#E6E1CF'

[colors.indexed]

[metadata]
name = 'ayu'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
