[colors]
ansi = [
  '#1e1e1e',
  '#be0f17',
  '#868715',
  '#d79921',
  '#458588',
  '#a04b73',
  '#689d6a',
  '#978771',
]
background = '#282828'
brights = [
  '#7f7061',
  '#f73028',
  '#aab01e',
  '#f7b125',
  '#719586',
  '#c77089',
  '#7db669',
  '#e6d4a3',
]
cursor_bg = '#928374'
cursor_border = '#928374'
cursor_fg = '#282828'
foreground = '#ebdbb2'
selection_bg = '#3c3836'
selection_fg = '#928374'

[colors.indexed]

[metadata]
name = 'gruvbox-dark'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
