[colors]
ansi = [
  '#000000',
  '#CC3E28',
  '#216609',
  '#B58900',
  '#1E6FCC',
  '#5C21A5',
  '#158c86',
  '#AAAAAA',
]
background = '#F2EEDE'
brights = [
  '#555555',
  '#CC3E28',
  '#216609',
  '#B58900',
  '#1E6FCC',
  '#5C21A5',
  '#158c86',
  '#AAAAAA',
]
cursor_bg = '#000000'
cursor_border = '#000000'
cursor_fg = '#F2EEDE'
foreground = '#000000'
selection_bg = '#d8d5c7'
selection_fg = '#000000'

[colors.indexed]

[metadata]
name = 'paper'
